### ISSUE TITLE
Googe Ads API Access

### ISSUE THREAD

**Issue by dmyers** [tmarois/laravel-ads-sdk#11]
Did you have to design a document to give to Google Ads in order to get API access?

My goal is mostly to just report offline conversions for ad campaigns myself, but it seems like getting API access is a big burden just so I can spend more money and was hoping to see if anyone else had any success.

**Comment by timothymarois** [comment]
Hey @dmyers, I have done offline conversion imports into Google, I created a few examples here on how you can import conversions. Let me know if this helps.

https://github.com/tmarois/laravel-ads-sdk/blob/master/GoogleAds-SDK.md#offline-conversion-import

As for the design document, that depends, usually, they don't require much for the basic access, if you need access approval, you can easily just write up a quick doc that says what your app is (such as using it internally for this need etc).

**Comment by dmyers** [comment]
Thank you @timothymarois. I really appreciate it! I started working on the implementation from the example code and it is very thorough and useful.

**Comment by timothymarois** [comment]
Thanks, @dmyers I use it for a lot of our needs, and over the years have been adding more features. If you do find more use-cases that this SDK doesn't have or additional modification, feel free to send in a request or pull and we can work to improve the feature-set. I've been so busy lately I haven't had a chance to dive back into this, but I'm sure some of the code could sure use refactoring. Don't hesitate to ask if you have any other questions.
