### ISSUE TITLE
I have a quastion about bing 

### ISSUE THREAD

**Issue by ashkesarmaa** [tmarois/laravel-ads-sdk#16]
to use bing api we should define BING_CLIENT_ID ,BING_CLIENT_SECRET ,BING_REFRESH_TOKEN and for get these information we have to register app in Azure portal. According to this document https://docs.microsoft.com/en-us/advertising/guides/authentication-oauth-identity-platform?view=bingads-13 we should provide the following information:

- Application / API Name
- What account types should be able to access this Application / API?
- Redirect URIs
- Any other additional relevant information

i really dont have any idea about that so would you please guide me about that or create a clear instruction to use bing 
Thank you so much
BR

**Comment by timothymarois** [comment]
Hi @ashkesarmaa 

So I understand what you're asking, you need help to authenticate this SDK to use the Bing Ads API?

**Comment by ashkesarmaa** [comment]
Hi @timothymarois 

Exactly because as you know bing document is not clear for me and i really need to understand how can i start using your package many thanks

BR

**Comment by timothymarois** [comment]
@ashkesarmaa Sorry about the delay, let me know if the instructions on here make sense: [bing authentication ](https://github.com/tmarois/laravel-ads-sdk/blob/master/BingAds-Auth.md) if not, feel free to join the [slack channel](https://join.slack.com/t/basephp/shared_invite/enQtNDI0MzQyMDE0MDAwLThlNjNlYWM3YWMxMjdhOGFiOTY1ZDFkMzUxMmUzZjJjM2JmZjI0YTg4MDYyYzc3OTc5MGIzYTdkNjQwMTQyNWY) and I can quickly explain how to set it up.

**Comment by ashkesarmaa** [comment]
@timothymarois  Many thanks to reply on my request i have a problem to setup yet so i guess i need to join slack channel as you mentioned because this link (Request Bing Ads API Access )in you document returns 404 error, Actually if you can record a toutrial about how can we use your package for bing and  upload it to YouTube it will be amazing.

BR

**Comment by timothymarois** [comment]
@ashkesarmaa I've updated the bing documentation, hopefully that helps in anyway. If you're still having trouble, feel free to ping me via slack.

**Comment by timothymarois** [comment]
Hello, it's been a while, but  I wanted to be sure you were able to get access to Bing Ads API. I have updated the Bing Ads Guide to access the API with the new steps they require. These steps worked for me as of June 3rd, 2021. 

https://github.com/tmarois/laravel-ads-sdk/blob/master/BingAds-Auth.md

Hopefully, this helps in your case and others that have had issues with connecting Bing. 

Feel free to [join the Discord server](https://discord.gg/g3W49zdWm2)
