### ISSUE TITLE
Client error: `POST https://oauth2.googleapis.com/token` resulted in a `400 Bad Request` response: { "error": "invalid_grant", "error_description": "Bad Request" }

### ISSUE THREAD

**Issue by prympineda** [tmarois/laravel-ads-sdk#17]
![2020-10-30_11h02_20](https://user-images.githubusercontent.com/29893038/97720554-5fbce980-1b03-11eb-9cc9-c3ba8fbf5213.png)

Hi, I got this issue every time I fetch a Campaign. Can you help me with the issue, please?

Here's my code from my controller.

![2020-10-30_22h59_51](https://user-images.githubusercontent.com/29893038/97720750-9a268680-1b03-11eb-91cd-84ab1c901de7.png)

I'm pretty sure that my credentials/API keys on .env are correct.

Thanks!

**Comment by timothymarois** [comment]
@prympineda Wanted to follow up here. Have you resolved your issue or is this still ongoing?

**Comment by SasanFouladi** [comment]
Hello
I have encountered exactly the same problem

**Comment by prajurit5639** [comment]
me too T_T
