### ISSUE TITLE
request-bing-ads-api-access

### ISSUE THREAD

**Issue by brasileric** [tmarois/laravel-ads-sdk#18]
This url (below) is not available anymore. I really don't understand how to get api access with Bing.

https://advertise.bingads.microsoft.com/en-us/resources/bing-partner-program/request-bing-ads-api-access

**Comment by timothymarois** [comment]
@brasileric Thanks for this report. Im going to look into this. Bing has been making a lot of changes lately.

**Comment by brasileric** [comment]
Thanks. It's very complex on the side of Bing indeed.

**Comment by timothymarois** [comment]
I've updated the documentation and added helpful pages that might guide you in the right direction. I will be running more tests in the next few months with both Google and Bing to be sure this SDK is up to date. If you're still having issues, feel free to submit a question regarding anything specific.

**Comment by timothymarois** [comment]
Hello, it's been a while, but  I wanted to be sure you were able to get access to Bing Ads API. I have updated the Bing Ads Guide to access the API with the new steps they require. These steps worked for me as of June 3rd, 2021. 

https://github.com/tmarois/laravel-ads-sdk/blob/master/BingAds-Auth.md

Hopefully, this helps in your case and others that have had issues with connecting Bing.
