### ISSUE TITLE
Bing Campaigns broken

### ISSUE THREAD

**Issue by maxSupermoney** [tmarois/laravel-ads-sdk#27]
Bing campaigns seem to have broken in commit [a37638c35a27b7e51e96162dab554d4814c819c2](https://github.com/tmarois/laravel-ads-sdk/commit/a37638c35a27b7e51e96162dab554d4814c819c2#diff-ae249aca354642f5cacd8ba1684f0aa0cd57989bbc7320e7b9bafc9c1d8a14d1)

Many of the Operation class methods were removed from CampaignOperations, and it does not extend the Operation class like AdGroupOperations so now there are missing methods.

Can we just extend the Operation class like AdGroupOperations does?

Trace
```
   Symfony\Component\Debug\Exception\FatalThrowableError  : Call to undefined method LaravelAds\Services\BingAds\Operations\Campaign::set()

  at /var/www/vhost/ad-data-gatherers/vendor/tmarois/laravel-ads-sdk/src/Services/BingAds/Service.php:196
    192|      */
    193|     public function campaign($campaign)
    194|     {
    195|         if ($campaign instanceof \stdClass) {
  > 196|             return (new Campaign($this))->set($campaign);
    197|         }
    198|
    199|         return (new Campaign($this))->setId($campaign)->get();
    200|     }

  Exception trace:

  1   LaravelAds\Services\BingAds\Service::campaign(Object(stdClass))
      /var/www/vhost/ad-data-gatherers/vendor/tmarois/laravel-ads-sdk/src/Services/BingAds/Fetch.php:59
```

**Comment by timothymarois** [comment]
Thanks for bringing that up, I believe that's an unreleased commit, maybe something @modernben can take a look at? I haven't had a chance to look over all the changes yet.
