### ISSUE TITLE
How to support lumen?

### ISSUE THREAD

**Issue by wenson** [tmarois/laravel-ads-sdk#37]
hi man，
run ` composer require tmarois/laravel-ads-sdk`  is ok.

but `php artisan vendor:publish`  is not work.

What's the next step?

thx a lot.

**Comment by wenson** [comment]

`
bootstrap app.php

//LaravelAds register
$app->register(\LaravelAds\Providers\LaravelAdsProvider::class);

// LaravelAds alias
$app->alias('LaravelAds',\LaravelAds\Facades\LaravelAds::class);`

Still no work

**Comment by timothymarois** [comment]
Hi,

I've not tested on the right install flow for Lumen yet, however, it runs like a regular composer package. The install for laravel is mainly for the config. You might be able to bypass that by running the manual config, like this example, and it might work as expected in your project. 

https://github.com/tmarois/laravel-ads-sdk/blob/master/GoogleAds-SDK.md#manual-configuration

**Comment by wenson** [comment]
it's ok.
```
composer require tmarois/laravel-ads-sdk

 bootstrap/app.php

//LaravelAds register
$app->register(\LaravelAds\Providers\LaravelAdsProvider::class);

// LaravelAds alias
$app->alias('LaravelAds',\LaravelAds\Facades\LaravelAds::class);

App\Http\Controllers\FacebookControllers.php

use LaravelAds\LaravelAds;
$facebookAds = LaravelAds::facebookAds()->with('1111111');
```

it's work now . but have another question .
