### ISSUE TITLE
Is there any function that updates the bid for keyword on bing api?

### ISSUE THREAD

**Issue by edwinjerez** [tmarois/laravel-ads-sdk#6]
Is there any function that updates the bid for keyword on bing api?
And what about the keyword performance report?
if not currently, when can I expect?

**Comment by timothymarois** [comment]
Hey @edwinjerez Currently, the SDK only allows for campaigns/adgroup bid changes. We do have search term performance, but not the keyword performance report. If this is important for you I can add this to the update list coming up.
