### ISSUE TITLE
V12 is now available?

### ISSUE THREAD

**Issue by edwinjerez** [tmarois/laravel-ads-sdk#7]
when I run the function eg: getCampaignReport for bing, I get the error like 

> 

Invalid client data. Check the SOAP fault details for more information
--
 

I tracked the error, but I found the error message is `This version of the Bing Ads API is no longer supported. Please migrate to the latest version of the API.`

this library need to updated to usd V13 for Bing?

**Comment by timothymarois** [comment]
hey @edwinjerez, which version of the SDK are you using? Bing should work with V13 as of the SDK version `1.2.13`. I will also look into `getCampaignReport` to be sure it's using V13.

**Comment by timothymarois** [comment]
@edwinjerez I ran a test on `getCampaignReport` and `getAdGroupReport` and both worked since the V13 change. Check that you're using the latest update of the Laravel Ads SDK. If you still see some issues, send more details of what you're trying to run and I can help you troubleshoot.

**Comment by edwinjerez** [comment]
> hey @edwinjerez, which version of the SDK are you using? Bing should work with V13 as of the SDK version `1.2.13`. I will also look into `getCampaignReport` to be sure it's using V13.

**Comment by edwinjerez** [comment]
> hey @edwinjerez, which version of the SDK are you using? Bing should work with V13 as of the SDK version `1.2.13`. I will also look into `getCampaignReport` to be sure it's using V13.

what sdk version you mean? tmarois/laravel-ads-sdk@1.2.13 you mean?

**Comment by timothymarois** [comment]
@edwinjerez That's correct.

**Comment by edwinjerez** [comment]
Actually the problem is that I`m using edujugon/laravel-google-ads, for managing the google ads api, and the googleads/googleads-php-lib is duplicate in both library.
for this reason, when I install your library, there are some issues like 
`tmarois/laravel-ads-sdk v1.2.14 requires googleads/googleads-php-lib ^40.0 -> satisfiable by 
googleads/googleads-php-lib[40.0.0].`
I`m trying myself, but if you have opinion, please let me know.

**Comment by edwinjerez** [comment]
I solved the version issue.
but it still get errors like 
`Invalid client data. Check the SOAP fault details for more information`

![image](https://user-images.githubusercontent.com/29590370/74893142-a2fe7000-5359-11ea-8b2e-24c8b3966366.png)

`public function getCampaigns() {
        $bingAds = LaravelAds::bingAds()->with('2688821');
        // dd($bingAds);
        $campaigns = $bingAds->reports('2020-01-15', '2020-02-15')
                           ->getCampaignReport();
        dd($campaigns);
    }`

**Comment by edwinjerez** [comment]
HI @timothymarois 
Please help me with this issue.
I think there is little issue on authorization.
I tried https://github.com/BingAds/BingAds-PHP-SDK/ with my credentials, and it`s working.
If I send my credentials can you check if it working in your library?
Thank you.

**Comment by timothymarois** [comment]
Hey. Join the slack and I can help troubleshoot your case.
https://join.slack.com/t/basephp/shared_invite/enQtNDI0MzQyMDE0MDAwLWU3Nzg0Yjk4MjM0OWVmZDZjMjEyYWE2YjA1ODFhNjI2MzI3MjAyOTIyOTRkMmVlNWNhZWYzMTIwZDJlOWQ2ZTA

**Comment by edwinjerez** [comment]
Hi.
I`m really sorry that I was away and your link has expired.
I will be appreciated if you send me the link again.
Thank you.

**Comment by edwinjerez** [comment]
Hi Timothy.
I really want your help.
Can you send me the invitation link again?

**Comment by edwinjerez** [comment]
Hi @timothymarois .
I really want your help.
Can you send me the invitation link again?

**Comment by timothymarois** [comment]
Hey, @edwinjerez here is an updated slack invite link. 

https://join.slack.com/t/basephp/shared_invite/enQtNDI0MzQyMDE0MDAwLThlNjNlYWM3YWMxMjdhOGFiOTY1ZDFkMzUxMmUzZjJjM2JmZjI0YTg4MDYyYzc3OTc5MGIzYTdkNjQwMTQyNWY

Also, sorry I received your email, I'm actually in Amsterdam for the week, but will try to respond when I'm online.
