### ISSUE TITLE
Where see I get the customer Client Id?

### ISSUE THREAD

**Issue by edwinjerez** [tmarois/laravel-ads-sdk#8]
// calling the Bing Ads Service and including the Customer Client Id
$bingAds = LaravelAds::bingAds()->with('CLIENT_ID');

What is this customer client Id and where can I get it?

**Comment by timothymarois** [comment]
Hey @edwinjerez If you go into your Bing account, and go to account settings, you want to find a page that has `Manage your account's settings and preferences.` You should see an `Account Id`, this is the client id, they renamed it a few times. I'll have to update the docs. Ironically, it is not the one that says "account number" which is a mix of letters/numbers.
