### ISSUE TITLE
Can't install and configure laravel-ads-sdk in my laravel project

### ISSUE THREAD

**Issue by cissecedric** [tmarois/laravel-ads-sdk#9]
Hi,

In my laravel project I successfully ad laravel ads with this cmd line :
`composer require tmarois/laravel-ads-sdk:^1.2`

My laravel project version is : Laravel Framework Lumen (5.4.7) (Laravel Components 5.4.*)

But then I m stuck, I can't configure anything related to laravel-ads

When I run this : `php artisan vendor:publish`
I get this error message ; There are no commands defined in the "vendor" namespace. 

And then I also get an error when running: 
`php artisan laravelads:token:generate --service=BingAds`
I get : There are no commands defined in the "laravelads:token" namespace.

I successfully  run `composer dump-autoload -o` but it didn't change nothing.

Any help would be very apreciated, 
Thank you in advance !
Regards

**Comment by timothymarois** [comment]
Hey @cissecedric

I’ll have to test with Lumen, at the moment it’s only been confirmed to
work on Laravel 5.5+, I’m currently in Amsterdam and heading back home end
of week, which I’ll be able to run some tests for you then. If you want to
quickly get going, make sure to have the newest version of lumen or
laravel.

**Comment by timothymarois** [comment]
HI, @cissecedric Checking in to see if you were able to get your project working. Feel free to jump into Slack if you need any help troubleshooting. (link on the readme)

**Comment by yashanandan** [comment]
Hi, I am having this issue in Lumen 8.3.1. Is it resolved or still open ?
